### ISSUE TITLE
Adapt to breaking change introduced in grpc-java 1.33

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#231]
The CogRPC dependencies don't work with grpc-java 1.33 or newer (e.g., v1.33.1), and I couldn't get to the bottom of it. I need to spend more time.

Based on the [changelog](https://github.com/grpc/grpc-java/releases/tag/v1.33.0), I think the culprit are the changes to the OkHTTP client.

Here's what happens when running an instrumentation test (`tech.relaycorp.courier.domain.PrivateSyncTest`):

```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;)V in class Lio/grpc/internal/AbstractManagedChannelImplBuilder; or its super classes (declaration of 'io.grpc.internal.AbstractManagedChannelImplBuilder' appears in /data/app/tech.relaycorp.courier-tX5wy5WksbsH6ebaU9nr9w==/base.apk:classes4.dex)
at io.grpc.okhttp.OkHttpChannelBuilder.<init>(OkHttpChannelBuilder.java:143)
at io.grpc.okhttp.OkHttpChannelBuilder.<init>(OkHttpChannelBuilder.java:139)
at io.grpc.okhttp.OkHttpChannelBuilder.forAddress(OkHttpChannelBuilder.java:107)
at tech.relaycorp.cogrpc.okhttp.OkHTTPChannelBuilderProvider.initChannelBuilder$relaynet_cogrpc_okhttp(OkHTTPChannelBuilderProvider.kt:13)
at tech.relaycorp.cogrpc.okhttp.OkHTTPChannelBuilderProvider.makeBuilder$relaynet_cogrpc_okhttp(OkHTTPChannelBuilderProvider.kt:18)
at tech.relaycorp.cogrpc.okhttp.OkHTTPChannelBuilderProvider$Companion.makeBuilder(OkHTTPChannelBuilderProvider.kt:36)
at tech.relaycorp.courier.domain.PrivateSyncTest$clientChannel$2.invoke(PrivateSyncTest.kt:50)
at tech.relaycorp.courier.domain.PrivateSyncTest$clientChannel$2.invoke(PrivateSyncTest.kt:21)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at tech.relaycorp.courier.domain.PrivateSyncTest.getClientChannel(Unknown Source:2)
at tech.relaycorp.courier.domain.PrivateSyncTest.access$getClientChannel$p(PrivateSyncTest.kt:21)
at tech.relaycorp.courier.domain.PrivateSyncTest$client$2.invoke(PrivateSyncTest.kt:60)
at tech.relaycorp.courier.domain.PrivateSyncTest$client$2.invoke(PrivateSyncTest.kt:21)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at tech.relaycorp.courier.domain.PrivateSyncTest.getClient(Unknown Source:2)
at tech.relaycorp.courier.domain.PrivateSyncTest.privateSync(PrivateSyncTest.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
```

See:

- #226.
- https://github.com/relaycorp/relaynet-cogrpc-jvm/pull/67
- https://github.com/relaycorp/relaynet-cogrpc-jvm-okhttp/commit/43bb5db92661022009045b2a90886a328b2057bc
