### ISSUE TITLE
Cargo delivery no longer works since upgrade to gRPC 1.58+

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#597]
# Describe the bug

Cargo delivery no longer works since upgrading gRPC to 1.60 in #586, because [gRPC 1.58.0](https://github.com/grpc/grpc-java/releases/tag/v1.58.0) removed the method `MetadataUtils.attachHeaders()` , [which is used in our CogRPC lib](https://github.com/relaycorp/awala-cogrpc-jvm/blob/e2ef9731ebed448b2b1e764cdb07afd8e4098fab/src/main/kotlin/tech/relaycorp/relaynet/cogrpc/client/CogRPCClient.kt#L162).

This causes the app to crash with:

```
2024-01-19 12:18:09.286 18390-18428 AndroidRuntime          pid-18390                            E  FATAL EXCEPTION: DefaultDispatcher-worker-7
                                                                                                    Process: tech.relaycorp.courier, PID: 18390
                                                                                                    java.lang.NoSuchMethodError: No static method attachHeaders(Lio/grpc/stub/AbstractStub;Lio/grpc/Metadata;)Lio/grpc/stub/AbstractStub; in class Lio/grpc/stub/MetadataUtils; or its super classes (declaration of 'io.grpc.stub.MetadataUtils' appears in /data/app/~~1Nupygb3i7dguQrgQH8WcQ==/tech.relaycorp.courier-90Mz_1bD4NH6lJz8et3vJQ==/base.apk!classes14.dex)
                                                                                                    	at tech.relaycorp.relaynet.cogrpc.client.CogRPCClient.buildAuthorizedClient(CogRPCClient.kt:162)
                                                                                                    	at tech.relaycorp.relaynet.cogrpc.client.CogRPCClient.access$buildAuthorizedClient(CogRPCClient.kt:33)
                                                                                                    	at tech.relaycorp.relaynet.cogrpc.client.CogRPCClient$collectCargo$1.invokeSuspend(CogRPCClient.kt:142)
                                                                                                    	at tech.relaycorp.relaynet.cogrpc.client.CogRPCClient$collectCargo$1.invoke(Unknown Source:12)
                                                                                                    	at tech.relaycorp.relaynet.cogrpc.client.CogRPCClient$collectCargo$1.invoke(Unknown Source:10)
                                                                                                    	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:320)
                                                                                                    	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3a813c5, Dispatchers.IO]
```

# How to reproduce

1. Sync data with Awala users.
2. Try to sync with the Internet.
3. Notice how the app crashes.

# Additional context

I started to fix this but didn't have enough time, so here's a few things I noticed which will come in handy:

- I _think_ we should be using `MetadataUtils.newAttachHeadersInterceptor()` instead, [which we're using in the tests](https://github.com/search?q=org%3Arelaycorp+MetadataUtils+path%3A*Test.kt&type=code), but for some reason weren't using at runtime.
- We should upgrade gRPC across the board to avoid these issues. That includes https://github.com/relaycorp/awala-cogrpc-jvm and https://github.com/relaycorp/awala-cogrpc-okhttp-jvm.
